// <auto-generated />
namespace MyClassLibrary.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class adminmodeladde : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adminmodeladde));
        
        string IMigrationMetadata.Id
        {
            get { return "202302271800398_admin model adde"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
