// <auto-generated />
namespace MyClassLibrary.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class patietmodelbgadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(patietmodelbgadded));
        
        string IMigrationMetadata.Id
        {
            get { return "202303010904515_patiet model bg added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
